# --*-- conding:utf-8 --*--
# @time:10/21/25 14:11
# @Author : Yuqi Zhang
# @Email : yzhan135@kent.edu
# @File:utils.py

"""
Misc utilities: XYZ writer for Cα traces and simple file helpers.
"""

from __future__ import annotations
from pathlib import Path
from typing import Iterable, Sequence, Tuple
import numpy as np


def write_xyz_ca(path: str | Path, coords: np.ndarray, sequence: str) -> None:
    """
    Write a minimalist XYZ file with one pseudo-atom per residue (Cα-only).
    Atom label uses the residue letter.

    XYZ format:
      <N>
      comment
      <elem> x y z
      ...

    Parameters
    ----------
    path : output file
    coords : (L,3) array
    sequence : length-L string of one-letter amino-acid codes
    """
    coords = np.asarray(coords, dtype=float)
    assert coords.ndim == 2 and coords.shape[1] == 3, "coords must be (L,3)"
    L = coords.shape[0]
    assert len(sequence) == L, "sequence length must match coords length"

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"{L}", "Cα-only XYZ generated by qsadpp"]
    for i in range(L):
        elem = sequence[i]
        x, y, z = coords[i]
        lines.append(f"{elem} {x:.6f} {y:.6f} {z:.6f}")
    p.write_text("\n".join(lines), encoding="utf-8")
